name: Deploy a Dockerized Node.js service to DigitalOcean

on:
  push:
    branches: [master, test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Droplet via SSH
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            cd /home/YOUR_USER/YOUR_PROJECT_DIR # 👈 if needed

            git pull origin master

            docker stop node-server || true
            docker rm node-server || true

            docker build -t entrecanales/node-server .

            docker run -d --name node-server \
              -e USER_NAME=${{ secrets.USER_NAME }} \
              -e PASSWORD=${{ secrets.PASSWORD }} \
              -e SECRET_MESSAGE="${{ secrets.SECRET_MESSAGE }}" \
              -p 8080:8080 entrecanales/node-server
EOF
