name: Deploy a Dockerized Node.js service to DigitalOcean

on:
  push:
      branches: [master, test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa #Give read permissions of ssh key
          ssh-keyscan -H ${{secrets.DROPLET_HOST}} >> ~/.ssh/host #Is this necessary?

      - name: Deploy to Droplet via SSH
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF' #Connect to droplet and enter the command
          #TODO: cd might be necessary here?

          git pull origin master

          docker build -t entrecanales/node-server .

          docker run -d --name node-server -e e USER_NAME=${{ secrets.USER_NAME }} -e PASSWORD=${{ secrets.PASSWORD }} -e SECRET_MESSAGE="${{ secrets.SECRET_MESSAGE }}" -p 8080:8080 node-service
